# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(version.major).$(version.minor).$(version.patch)-alpha$(buildcount)

variables:
  MajorVersion: $(version.major)
  MinorVersion: $(version.minor)
  PatchVersion: $(version.patch)
  BuildCount: $[counter('buildcount', 5)]
  NugetKey: $(key.nuget)

jobs:
- job: InstallPrereqs
  displayName: 'Install Build Pre-requisites'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      packageType: 'sdk'
      version: '2.1.403'

- job: Build
  dependsOn: InstallPrereqs
  displayName: 'Build and Publish TypeScript Core Tools'
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: custom
      custom: msbuild
      projects: build/build.proj
      arguments: /p:MajorVersion=$(MajorVersion) /p:MinorVersion=$(MinorVersion) /p:PatchVersion=$(PatchVersion) /p:VersionSuffix=alpha$(BuildCount) /p:NuGetApiKey=$(NugetKey)
