# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  MajorVersion: $(version.major)
  MinorVersion: $(version.minor)
  PatchVersion: $(version.patch)
  BuildCount: $[counter('buildcount', 5)]
  NugetKey: $(key.nuget)

name: $(version.major).$(version.minor).$(version.patch)-alpha$(buildcount)

steps:
- script: npm install -g typescript@latest
  displayName: 'Install TypeScript'

- script: dotnet msbuild build/build.proj /p:MajorVersion=$MAJORVERSION /p:MinorVersion=$MINORVERSION /p:PatchVersion=$PATCHVERSION /p:VersionSuffix=alpha$BUILDCOUNT /p:NuGetApiKey=$NUGETKEY
  displayName: 'Build and Publish'
  env:
    NUGETKEY: $(NugetKey)
